# -*- coding: utf-8 -*-
#
# Anki Stat Scraper Add-on for Anki
# Copyright (C)  2022 Carlos Georges <carlosgeorges.com>
#
# This file was automatically generated by Anki Add-on Builder v0.1.4
# It is subject to the same licensing terms as the rest of the program
# (see the LICENSE file which accompanies this program).
#
# WARNING! All changes made in this file will be lost!

"""
Initializes generated Qt forms/resources
"""

__all__ = [
    "form"
]

from . import form
