# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.exportButton = QtWidgets.QPushButton(Dialog)
        self.exportButton.setGeometry(QtCore.QRect(350, 390, 80, 25))
        self.exportButton.setObjectName("exportButton")
        self.name_container = QtWidgets.QWidget(Dialog)
        self.name_container.setGeometry(QtCore.QRect(260, 80, 120, 80))
        self.name_container.setObjectName("name_container")
        self.name_label = QtWidgets.QLabel(self.name_container)
        self.name_label.setGeometry(QtCore.QRect(0, 10, 51, 17))
        self.name_label.setObjectName("name_label")
        self.name_entry = QtWidgets.QLineEdit(self.name_container)
        self.name_entry.setGeometry(QtCore.QRect(0, 30, 113, 25))
        self.name_entry.setObjectName("name_entry")
        self.nshe_container = QtWidgets.QWidget(Dialog)
        self.nshe_container.setGeometry(QtCore.QRect(410, 80, 120, 80))
        self.nshe_container.setObjectName("nshe_container")
        self.nshe_label = QtWidgets.QLabel(self.nshe_container)
        self.nshe_label.setGeometry(QtCore.QRect(0, 10, 51, 17))
        self.nshe_label.setObjectName("nshe_label")
        self.nshe_entry = QtWidgets.QLineEdit(self.nshe_container)
        self.nshe_entry.setGeometry(QtCore.QRect(0, 30, 113, 25))
        self.nshe_entry.setObjectName("nshe_entry")
        self.output_box = QtWidgets.QPlainTextEdit(Dialog)
        self.output_box.setGeometry(QtCore.QRect(260, 180, 271, 181))
        self.output_box.setObjectName("output_box")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.exportButton.setText(_translate("Dialog", "Export"))
        self.name_label.setText(_translate("Dialog", "Name:*"))
        self.nshe_label.setText(_translate("Dialog", "NSHE:*"))
